[alias]
cargo-machete = "ubi:bnjbvr/cargo-machete"

[tools]
actionlint = "latest"

[tasks."example-server:curl"]
description = "Call example server via curl"
run = "curl -vvv --digest --user \"Spy:vs. Spy\" http://127.0.0.1:1337/"

[tasks."example-server:run"]
description = "Run example server"
run = "cargo run --example server"
sources = ["Cargo.toml", "src/**/*.rs", "examples/server.rs"]
outputs = ["target/debug/examples/server"]

[tasks.lint]
description = "Lint project"
depends = [
  "lint:clippy",
  "lint:rust-unused-deps",
  "lint:rustfmt",
  "lint:taplo",
  "lint:taplo-format",
]

[tasks."lint:clippy"]
description = "Lints Rust files with Clippy"
run = "cargo clippy --all-features --all-targets --workspace"

[tasks."lint:rust-unused-deps"]
tools.cargo-machete = "latest"
description = "Checks if there are any unused crate dependencies declared"
run = "cargo machete"

[tasks."lint:rustfmt"]
description = "Checks if Rust files are formatted correctly"
run = "cargo fmt --all --check"

[tasks."lint:taplo"]
tools.taplo = "latest"
description = "Lints TOML files with Taplo"
run = "taplo lint"

[tasks."lint:taplo-format"]
tools.taplo = "latest"
description = "Checks if TOML files are formatted correctly"
run = "taplo format --check --diff"
