(function() {var implementors = {};
implementors["futures"] = [];
implementors["hyper"] = [{"text":"impl Stream for Body","synthetic":false,"types":[]},{"text":"impl&lt;I, S, B&gt; Stream for Serve&lt;I, S&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;I: Stream&lt;Error = Error&gt;,<br>&nbsp;&nbsp;&nbsp;&nbsp;I::Item: AsyncRead + AsyncWrite,<br>&nbsp;&nbsp;&nbsp;&nbsp;S: NewService&lt;Request = Request, Response = Response&lt;B&gt;, Error = Error&gt;,<br>&nbsp;&nbsp;&nbsp;&nbsp;B: Stream&lt;Error = Error&gt;,<br>&nbsp;&nbsp;&nbsp;&nbsp;B::Item: AsRef&lt;[u8]&gt;,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl Stream for AddrIncoming","synthetic":false,"types":[]}];
implementors["tokio_core"] = [{"text":"impl Stream for Incoming","synthetic":false,"types":[]},{"text":"impl&lt;C:&nbsp;UdpCodec&gt; Stream for UdpFramed&lt;C&gt;","synthetic":false,"types":[]},{"text":"impl Stream for Interval","synthetic":false,"types":[]}];
implementors["tokio_fs"] = [{"text":"impl Stream for ReadDir","synthetic":false,"types":[]}];
implementors["tokio_io"] = [{"text":"impl&lt;A&gt; Stream for Lines&lt;A&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;A: AsyncRead + BufRead,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["tokio_proto"] = [{"text":"impl&lt;T, E&gt; Stream for Body&lt;T, E&gt;","synthetic":false,"types":[]}];
implementors["tokio_sync"] = [{"text":"impl&lt;T&gt; Stream for Receiver&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T&gt; Stream for UnboundedReceiver&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Clone&gt; Stream for Receiver&lt;T&gt;","synthetic":false,"types":[]}];
implementors["tokio_tcp"] = [{"text":"impl Stream for Incoming","synthetic":false,"types":[]}];
implementors["tokio_timer"] = [{"text":"impl&lt;T&gt; Stream for DelayQueue&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Stream&gt; Stream for Throttle&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T&gt; Stream for Timeout&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: Stream,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl Stream for Interval","synthetic":false,"types":[]}];
implementors["tokio_udp"] = [{"text":"impl&lt;C:&nbsp;Decoder&gt; Stream for UdpFramed&lt;C&gt;","synthetic":false,"types":[]}];
implementors["tokio_uds"] = [{"text":"impl&lt;A, C:&nbsp;Decoder&gt; Stream for UnixDatagramFramed&lt;A, C&gt;","synthetic":false,"types":[]},{"text":"impl Stream for Incoming","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()