name: Daily Lints

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust via mise
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11
        with:
          experimental: true
          tool_versions: |
            cargo-machete latest
            taplo latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run linters
        run: mise run lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
